include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    unrelated_type_equality_checks: true
    collection_methods_unrelated_type: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    unrelated_type_equality_checks: error
    collection_methods_unrelated_type: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
